change to only use ensurepip if present

diff --git a/bin/steps/python b/bin/steps/python
--- a/bin/steps/python
+++ b/bin/steps/python
@@ -126,34 +126,37 @@ if [ ! "$SKIP_INSTALL" ]; then
   hash -r
 fi
 
+# Testing ensurepip bootstrapping
+if [[ /app/.heroku/python/bin/pip3 --version ]]; then
+  if [[ /app/.heroku/python/bin/pip3 --version | grep -q $PIP_UPDATE ]]
+    /app/.heroku/python -m ensurepip --upgrade
+  fi
+else
 
-# /app/.heroku/python/bin/python -m ensurepip
 
-/app/.heroku/python/bin/pip3 --version
+  # Heroku uses the get-pip utility maintained by the Python community to vendor Pip.
+  # https://github.com/pypa/get-pip
+  GETPIP_URL="https://lang-python.s3.amazonaws.com/etc/get-pip.py"
+  GETPIP_PY="${TMPDIR:-/tmp}/get-pip.py"
 
+  if ! curl -s "${GETPIP_URL}" -o "$GETPIP_PY" &> /dev/null; then
+      mcount "failure.python.get-pip"
+      echo "Failed to pull down get-pip"
+      exit 1
+  fi
 
-# Heroku uses the get-pip utility maintained by the Python community to vendor Pip.
-# https://github.com/pypa/get-pip
-GETPIP_URL="https://lang-python.s3.amazonaws.com/etc/get-pip.py"
-GETPIP_PY="${TMPDIR:-/tmp}/get-pip.py"
+  # If Pip isn't up to date:
+  if [ "$FRESH_PYTHON" ] || [[ ! $(pip --version) == *$PIP_UPDATE* ]]; then
 
-if ! curl -s "${GETPIP_URL}" -o "$GETPIP_PY" &> /dev/null; then
-    mcount "failure.python.get-pip"
-    echo "Failed to pull down get-pip"
-    exit 1
-fi
+    puts-step "Installing pip"
 
-# If Pip isn't up to date:
-if [ "$FRESH_PYTHON" ] || [[ ! $(pip --version) == *$PIP_UPDATE* ]]; then
+    # Remove old installations.
+    rm -fr /app/.heroku/python/lib/python*/site-packages/pip-*
+    rm -fr /app/.heroku/python/lib/python*/site-packages/setuptools-*
 
-  puts-step "Installing pip"
-
-  # Remove old installations.
-  rm -fr /app/.heroku/python/lib/python*/site-packages/pip-*
-  rm -fr /app/.heroku/python/lib/python*/site-packages/setuptools-*
-
-  /app/.heroku/python/bin/python "$GETPIP_PY" pip=="$PIP_UPDATE" &> /dev/null
-  /app/.heroku/python/bin/pip install "$ROOT_DIR/vendor/setuptools-39.0.1-py2.py3-none-any.whl" &> /dev/null
+    /app/.heroku/python/bin/python "$GETPIP_PY" pip=="$PIP_UPDATE" &> /dev/null
+    /app/.heroku/python/bin/pip install "$ROOT_DIR/vendor/setuptools-39.0.1-py2.py3-none-any.whl" &> /dev/null
+  fi
 fi
 
 set -e
